all: step0_repl

step0_repl: step0_repl.c
	gcc -ledit -o step0_repl step0_repl.c

step1_read_print: step1_read_print.c
	gcc -ggdb -ledit -o step1_read_print step1_read_print.c types.c reader.c ll.c/ll.c
